name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push backend image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build ./alpha-vantage-task-backend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}

    - name: 'Build and push frontend image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build ./alpha-vantage-task-frontend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

    - name: 'Deploy to Azure Web App for Backend'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alpha-vantage-task-backend'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}'

    - name: 'Deploy to Azure Web App for Frontend'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alpha-vantage-task-frontend'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}'